# Example Amass Configuration File
# Copy this file and customize for your environment
# Documentation: https://github.com/owasp-amass/amass/blob/master/doc/user_guide.md#configuration-file

# DNS settings
[dns]
# Maximum number of recursive queries for each subdomain enumerated
max_dns_queries = 20000

# DNS resolvers to use for subdomain enumeration
resolvers = [
    "8.8.8.8",
    "8.8.4.4",
    "1.1.1.1",
    "1.0.0.1",
    "9.9.9.9",
    "149.112.112.112"
]

# Rate limiting settings
[rate_limit]
# Number of DNS queries per second
rate = 500

# Network settings
[network]
# Maximum number of connections
max_connections = 200

# Timeout for network connections (seconds)
timeout = 30

# Data source settings
[data_sources]

# AlienVault OTX
[data_sources.AlienVault]
[data_sources.AlienVault.Credentials]
apikey = "your_alienvault_api_key_here"

# Bing
[data_sources.Bing]
[data_sources.Bing.Credentials]
apikey = "your_bing_api_key_here"

# BinaryEdge
[data_sources.BinaryEdge]
[data_sources.BinaryEdge.Credentials]
apikey = "your_binaryedge_api_key_here"

# Censys
[data_sources.Censys]
[data_sources.Censys.Credentials]
apikey = "your_censys_api_key_here"
secret = "your_censys_secret_here"

# Chaos
[data_sources.Chaos]
[data_sources.Chaos.Credentials]
apikey = "your_chaos_api_key_here"

# CIRCL
[data_sources.CIRCL]
[data_sources.CIRCL.Credentials]
username = "your_circl_username_here"
password = "your_circl_password_here"

# GitHub
[data_sources.GitHub]
[data_sources.GitHub.Credentials]
apikey = "your_github_token_here"

# Hunter
[data_sources.Hunter]
[data_sources.Hunter.Credentials]
apikey = "your_hunter_api_key_here"

# IntelX
[data_sources.IntelX]
[data_sources.IntelX.Credentials]
apikey = "your_intelx_api_key_here"

# PassiveTotal
[data_sources.PassiveTotal]
[data_sources.PassiveTotal.Credentials]
username = "your_passivetotal_username_here"
apikey = "your_passivetotal_api_key_here"

# SecurityTrails
[data_sources.SecurityTrails]
[data_sources.SecurityTrails.Credentials]
apikey = "your_securitytrails_api_key_here"

# Shodan
[data_sources.Shodan]
[data_sources.Shodan.Credentials]
apikey = "your_shodan_api_key_here"

# Spyse
[data_sources.Spyse]
[data_sources.Spyse.Credentials]
apikey = "your_spyse_api_key_here"

# ThreatBook
[data_sources.ThreatBook]
[data_sources.ThreatBook.Credentials]
apikey = "your_threatbook_api_key_here"

# Umbrella
[data_sources.Umbrella]
[data_sources.Umbrella.Credentials]
apikey = "your_umbrella_api_key_here"

# URLVoid
[data_sources.URLVoid]
[data_sources.URLVoid.Credentials]
apikey = "your_urlvoid_api_key_here"

# VirusTotal
[data_sources.VirusTotal]
[data_sources.VirusTotal.Credentials]
apikey = "your_virustotal_api_key_here"

# WhoisXML
[data_sources.WhoisXML]
[data_sources.WhoisXML.Credentials]
apikey = "your_whoisxml_api_key_here"

# ZoomEye
[data_sources.ZoomEye]
[data_sources.ZoomEye.Credentials]
username = "your_zoomeye_username_here"
password = "your_zoomeye_password_here"

# Wordlist settings for brute force
[bruteforce]
# Enable brute force enumeration
enabled = false

# Minimum number of characters for generated names
min_for_recursive = 1

# Wordlists to use for brute force (optional)
# wordlists = [
#     "/path/to/wordlist1.txt",
#     "/path/to/wordlist2.txt"
# ]

# Output settings
[output]
# Directory to save results
output_directory = "./amass_output"

# Output formats
formats = ["txt", "json"]

# Include sources in output
include_sources = true

# Database settings (optional)
[database]
# Database type: postgres, mysql, or sqlite3
# type = "sqlite3"
# connection_string = "./amass.db"

# Scope settings
[scope]
# Maximum depth for subdomain recursion
max_depth = 5

# Domains to exclude from enumeration
# blacklist = ["excluded-domain.com"]

# IP ranges to exclude
# exclude_ips = ["192.168.1.0/24", "10.0.0.0/8"]
